default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: example
  host: localhost
  encoding: utf8mb4
  collation: utf8mb4_bin


development:
  <<: *default
  database: twitch_crawler_development
  host: 127.0.0.1


test:
  <<: *default
  database: twitch_crawler
  host: 127.0.0.1

production:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") %>
  database: twitch_crawler
  username: twtich_crawler
  password: <%= ENV.fetch("DB_PASSWORD") %>
